"""empty message

Revision ID: c76fb81b19e6
Revises: be76b22c75b4
Create Date: 2023-07-27 22:14:19.420510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76fb81b19e6'
down_revision = 'be76b22c75b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.Column('Room_pin', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.drop_table('guest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('Room_pin', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='guest_pkey'),
    sa.UniqueConstraint('Name', name='guest_Name_key')
    )
    op.drop_table('room')
    # ### end Alembic commands ###
